import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'revenue-cycle-overview',
    {
      type: 'category',
      label: 'Packages',
      items: [
        { type: 'autogenerated', dirName: 'migrations' },
        { type: 'autogenerated', dirName: 'mcp-server' },
        { type: 'autogenerated', dirName: 'shared-types' },
        { type: 'autogenerated', dirName: 'infrastructure' },
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      items: [{ type: 'autogenerated', dirName: 'workflows' }],
    },
  ],
}

export default sidebars
